### ISSUE TITLE
Event Banner image output

### ISSUE THREAD

**Issue by yvsdrop** [dl-stuff/dl-wiki-scripts#4]
Currently the image processing script has all event banners mapped to the Void Battles Banners category:

`'Void_Battles_Banners': re.compile(r'^EventQuestMenu(List|Top)\d{2}$'),`

I don't think there's a good way to differentiate them based on Image name itself (maybe if paired with mono data) so perhaps it'd be safer (or at least, easier to find in the output) if it mapped to "Event Banners" instead? Alternatively maybe don't map at all?

I haven't really analyzed it though, so maybe there actually is a way to tell void banners from event banners other than needing to look at game data.

**Comment by Mushymato** [comment]
yea im not entirely sure either, will rename to Event_Banners for now
